name: Go
on: [push]
jobs:

  vet:
    name: Vet
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.22
      uses: actions/setup-go@v4
      with:
        go-version: 1.22
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Vet
      run: make vet

